---
language: python
python:
    - "3.8"
before_install:
    - mv travis_secrets.yaml secrets.yaml
    - sudo add-apt-repository -y ppa:jonathonf/ffmpeg-4
    - sudo apt-get install -y libudev-dev ffmpeg

install:
    - pip3 install homeassistant
script:
    - hass -c . --script check_config --info all
