- id: '1644127100239'
  alias: Dim lights based on sun elevation
  description: ''
  use_blueprint:
    path: EvTheFuture/dim_lights_based_on_sun_elevation.yaml
    input:
      min_brightness: 40
      turn_on: true
      target_lights:
        area_id:
        - 5fe667de18094e0aa0eac0812743ff0a
        - 2ef487b8abbd4a4084c3d681290725b2
        - 6553e27bd35941e6b8217ca2a7e36751
        - f8941279e2ec472f96ab086d3a50ab75
- id: '1651064077285'
  alias: Ada's Lights - Blue Button
  description: ''
  use_blueprint:
    path: slashback/trigger-different-actions-on-a-single-double-or-double-click-on-a-binary-sensor.yaml
    input:
      switch_id: binary_sensor.adas_blue_button
      long_click_action:
      - service: light.turn_off
        data: {}
        target:
          area_id: 5fe667de18094e0aa0eac0812743ff0a
      short_click_action:
      - service: light.turn_on
        data:
          brightness_pct: 100
        target:
          area_id: 5fe667de18094e0aa0eac0812743ff0a
      double_click_action:
      - service: light.turn_on
        data:
          brightness: 80
        target:
          area_id: 5fe667de18094e0aa0eac0812743ff0a
- id: '1651101346989'
  alias: Ada's Lights - Yellow Button
  description: ''
  use_blueprint:
    path: slashback/trigger-different-actions-on-a-single-double-or-double-click-on-a-binary-sensor.yaml
    input:
      switch_id: binary_sensor.adas_yellow_button
      short_click_action:
      - service: light.turn_on
        data_template:
          hs_color:
          - '{{ (30 + (state_attr(''light.adas_room_light'', ''hs_color'')[0] or 0))
            % 360 }}'
          - 100
          brightness_pct: 100
          transition: 1
        target:
          entity_id: light.adas_room_light
