- id: '1651064077285'
  alias: Ada's Lights - Blue Button
  description: ''
  use_blueprint:
    path: slashback/trigger-different-actions-on-a-single-double-or-double-click-on-a-binary-sensor.yaml
    input:
      switch_id: binary_sensor.adas_blue_button
      long_click_action:
      - service: light.turn_on
        data:
          white: 25
          brightness_pct: 10
        target:
          entity_id: light.adas_room_light
      short_click_action:
      - service: light.turn_on
        data:
          white: 255
          brightness_pct: 100
        target:
          entity_id: light.adas_room_light
      double_click_action: []
- id: '1651101346989'
  alias: Ada's Lights - Yellow Button
  description: ''
  use_blueprint:
    path: slashback/trigger-different-actions-on-a-single-double-or-double-click-on-a-binary-sensor.yaml
    input:
      switch_id: binary_sensor.adas_yellow_button
      short_click_action:
      - service: light.turn_on
        data_template:
          hs_color:
          - '{{ (60 + (state_attr(''light.adas_room_light'', ''hs_color'')[0] or 0))
            % 360 }}'
          - 100
          brightness_pct: 100
          transition: 1
        target:
          entity_id: light.adas_room_light
- id: '1651108558107'
  alias: New Automation
  description: ''
  use_blueprint:
    path: slashback/trigger-different-actions-on-a-single-double-or-double-click-on-a-binary-sensor.yaml
    input:
      switch_id: binary_sensor.adas_green_button
      short_click_action:
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.adas_room_light
- id: '1672316191485'
  alias: Washing Cycle Done
  description: ''
  trigger:
  - platform: state
    entity_id:
    - select.washing_machine_state
    from: DEVICE_STATE_RUNNING
    to: DEVICE_STATE_ON
  condition:
  - condition: time
    after: 06:00:00
    before: '22:00:00'
  action:
  - service: tts.cloud_say
    data:
      entity_id: media_player.kitchen_home
      message: The washing machine has finished it's cycle
  mode: single
- id: '1684069946267'
  alias: Trigger Bedtime Routine with Phone Charge
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.danny_asleep
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    after: '20:30:00'
    before: 01:00:00
  action:
  - service: script.bedtime
    data: {}
  mode: single
- id: '1704546738005'
  alias: Turn off AC when outside temp is lower than inside temp an the input temp
    is reasonable
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.melbourne_temp
    below: 21
    for:
      minutes: 30
  - platform: numeric_state
    entity_id: sensor.home_average_temperature
    below: 23
    for:
      minutes: 30
  condition:
  - and:
    - alias: Night mode is on
      condition: state
      entity_id: input_boolean.hot_night_mode
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.deck_temperature
      below: 21
    - condition: numeric_state
      entity_id: sensor.home_average_temperature
      below: 23
  action:
  - service: climate.turn_off
    entity_id: climate.central_cooling
  - service: input_boolean.turn_off
    entity_id: input_boolean.hot_night_mode
  mode: single
- id: '1709121550654'
  alias: Turn off AC when outside temp is lower than inside temp an the input temp
    is reasonable
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.melbourne_temp
    below: 21
    for:
      minutes: 30
  - platform: numeric_state
    entity_id: sensor.home_average_temperature
    below: 23
    for:
      minutes: 30
  condition:
  - and:
    - alias: Night mode is on
      condition: state
      entity_id: input_boolean.hot_night_mode
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.deck_temperature
      below: 21
    - condition: numeric_state
      entity_id: sensor.home_average_temperature
      below: 23
  action:
  - service: climate.turn_off
    entity_id: climate.central_cooling
  - service: input_boolean.turn_off
    entity_id: input_boolean.hot_night_mode
  mode: single
- id: '1740831049335'
  alias: Tag Bedtime Explorers is scanned
  description: ''
  triggers:
  - trigger: tag
    tag_id: 22495f36-8cf0-4bad-a28f-40ef6c52b818
  conditions: []
  actions:
  - action: spotcast.start
    data:
      random_song: true
      device_name: Ada's Room speaker
      uri: spotify:playlist:7ayGiIqf6AYkz4MdJmFO0J
  mode: single
- id: '1746790764389'
  alias: Toothbrushing Reminder
  description: ''
  triggers:
  - at: 07:39:00
    trigger: time
  conditions: []
  actions:
  - action: openai_conversation.generate_content
    data:
      prompt: "My daughters need to brush their teeth. \nTheir names are Ada and Leni.
        They are 6 and 3 years old.\nI need a message to send to my home automation
        system to notify over a speaker. \nmake it funny and novel and appropriate
        to their age.\nResponse with at most one response, it should not list options
        or have any other surrounding text, \njust the message for the girls. keep
        it short and sweet, and funny.\nAlways begin with a greeting to the two girls\nNo
        emojis, no asrerisk or underscores, you're writing a script for a tts.\nMix
        it up, DO NOT always talk about being super heros fighting cavities or sugarbugs/monsters
        etc, .. sometimes just tell them to brush their teeth  with humour, perhaps
        even sarcasm\n\n"
      config_entry: 01JTTBH3JQ7CYM3YMM4EJGNMWK
    response_variable: message
  - action: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.7
    target:
      entity_id: media_player.kitchen_home
  - action: tts.amazon_polly_say
    metadata: {}
    data:
      cache: false
      entity_id: media_player.kitchen_home
      message: '{{message.text}}'
      options:
        voice: Amy
        engine: generative
      language: en-GB
  mode: single
- id: '1746827000348'
  alias: Joke Time
  description: ''
  triggers:
  - at: '17:50:00'
    trigger: time
  conditions: []
  actions:
  - action: openai_conversation.generate_content
    data:
      config_entry: 01JTTBH3JQ7CYM3YMM4EJGNMWK
      prompt: 'Tell a joke suitable for a 6 year old.

        '
    response_variable: message
  - action: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.6
    target:
      entity_id: media_player.kitchen_home
  - action: tts.amazon_polly_say
    metadata: {}
    data:
      entity_id: media_player.kitchen_home
      message: '{{message.text}}'
      language: en-GB
      options:
        voice: Amy
        engine: generative
  - action: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.5
    target:
      entity_id: media_player.kitchen_home
  mode: single
- id: '1747172761610'
  alias: Get ready music morning
  description: ''
  triggers:
  - trigger: time
    at: 07:25:00
  conditions: []
  actions:
  - action: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.5
    target:
      entity_id: media_player.kitchen_home
  - action: spotcast.start
    metadata: {}
    data:
      force_playback: true
      uri: spotify:track:7vMeyV4cZSqFSHm6WIyVjB
      entity_id: media_player.kitchen_home
  mode: single
