
- alias: Bedroom Heating On
  trigger:
    platform: time
    at: "19:00:00"
  action:
  - service: climate.turn_on
    data:
      entity_id: climate.bedroom
  - service: climate.set_temperature
    data:
      entity_id: climate.bedroom
      temperature: 18
      operation_mode: Heat
- alias: Bedroom Heating Off
  trigger:
    platform: time
    at: "08:00:00"
  action:
  - service: climate.turn_off
    data:
      entity_id: climate.bedroom
   