- id: '1628039924697'
  alias: New Automation
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition:
  - condition: state
    entity_id: person.danny
    state: home
  - condition: and
    conditions:
    - condition: state
      entity_id: person.gemma
      state: home
  action:
  - service: light.turn_off
    target:
      device_id: 9fd68456fa7511ea986b75998eacf5e1
  mode: single
