# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
lovelace:
  mode: yaml
discovery:
homeassistant:
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret api_password
http:
#stream:
# android_ip_webcam: !include components/android_ip_webcam.yaml
sensor: !include_dir_merge_list sensors/
# binary_sensor: !include components/binary_sensor.yaml
device_tracker: !include components/device_tracker.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
fan: !include components/fan.yaml
frontend: !include components/frontend.yaml
light: !include components/light.yaml
climate: !include components/climate.yaml
switch: !include components/switch.yaml
camera: !include components/camera.yaml
media_player: !include components/media_player.yaml
weather: !include components/weather.yaml
input_select: !include components/input_select.yaml
input_boolean: !include components/input_boolean.yaml
speedtestdotnet: !include components/speedtestdotnet.yaml
system_health:
tts:
  - platform: google_translate
tuya:
  username: !secret email
  password: !secret tuya_password
  country_code: 61
  platform: 'tuya'
tplink:
ffmpeg:
upnp:
  port_mapping: true
  sensors: false
wunderlist:
  client_id: !secret wunderlist_client_id
  access_token: !secret wunderlist_access_token
spotcast:
  username: !secret spotify_username
  password: !secret spotify_password

panel_iframe:
  router:
    title: 'Router'
    url: !secret router_homepage
  fridge:
    title: 'Ferm Fridge'
    url: !secret ferm_fridge_homepage

history_graph:
  aqi:
    name: AQI Graph
    entities:
      - sensor.livingroom_aqi
    hours_to_show: 72
    refresh: 60

python_script:

