---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
lovelace:
  mode: yaml
  resources:
    - url: /local/community/lovelace-card-mod/card-mod.js
      type: module
    - url: /local/community/config-template-card/config-template-card.js
      type: module
    - url: /local/custom-lovelace/air-purifier/card.js
      type: module
    - url: /local/custom-lovelace/mini-graph-card-bundle.js?v=0.9.4
      type: module
    - url: /local/community/canvas-gauge-card/canvas-gauge-card.js
      type: module
    - url: /local/community/rgb-light-card/card.js
      type: module
    - url: /local/community/bom-radar-card/bom-radar-card.js
      type: module
    - url: /local/community/purifier-card/purifier-card.js
      type: module
    - url: /local/community/lovelace-mushroom/mushroom.js
      type: module
    - url: /local/community/stack-in-card/stack-in-card.js
      type: module
    - url: /local/community/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /local/community/lovelace-layout-card/layout-card.js
      type: module
    - url: /local/community/lovelace-clock-card/clock-card.js
      type: module
homeassistant:
  auth_providers:
    - type: homeassistant
  packages: !include_dir_named packages
http:
#stream:
# android_ip_webcam: !include components/android_ip_webcam.yaml
sensor: !include_dir_merge_list sensors/
binary_sensor: !include components/binary_sensor.yaml
# device_tracker: !include components/device_tracker.yaml
# group: !include groups.yaml
automation mine: !include_dir_merge_list automations
automation: !include automations.yaml
script: !include scripts.yaml
frontend: !include components/frontend.yaml
climate: !include components/climate.yaml
switch: !include components/switch.yaml
mqtt: !include components/mqtt.yaml
input_select: !include components/input_select.yaml
input_boolean: !include components/input_boolean.yaml
system_health:
tts:
  - platform: google_translate
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key
    aws_secret_access_key: !secret aws_secret_access_key
# tuya:
#   username: !secret email
#   password: !secret tuya_password
#   country_code: 61
#   platform: "tuya"
ffmpeg:
# option removed
# google:
#   client_id: !secret google_api_client_id
#   client_secret: !secret google_api_client_secret

python_script:

recorder:
  purge_keep_days: 28
  auto_purge: true

spotcast:
  sp_dc: !secret spotify_dc
  sp_key: !secret spotify_key
  country: AU

logger:
  default: warning

utility_meter:
  central_heating_hours:
    source: switch.central_heating_power
    cycle: daily

  daily_family_room_heater_energy:
    source: sensor.family_room_wall_unit_power_consumption
    cycle: daily

  weekly_family_room_heater_energy:
    source: sensor.family_room_wall_unit_power_consumption
    cycle: weekly

  monthly_family_room_heater_energy:
    source: sensor.family_room_wall_unit_power_consumption
    cycle: monthly

notify:
  - platform: ai_notify
    name: ai_notify
    api_key: !secret openai_api_key 
    tts_service: "tts.google_translate_say"
    default_media_player: "media_player.kitchen_home"
    prompt_templates:
      default: "Please rephrase the following message in a creative way: '{message}'"
      ada: >
        You will be talking to a 7yo. Make following message engaging and funny but still
        convey the intent of the message, The idea is to not become boring: 
        ---
        '{message}'
      formal: "Rephrase this message formally: '{message}'"

template:
  - sensor:
      - name: Current Week Meal Trello List
        state: >
          {% set week_number = now().isocalendar().week %}
          {% set lists = state_attr('sensor.trello_meal_lists', 'lists') %}
          {% if lists %}
            {{ lists[week_number % lists | length]['id'] }}
          {% else %}
            "Unknown"
          {% endif %}
