title: Home
views: !include_dir_list lovelace/views
resources:
  - url: /local/lovelace-fullykiosk.js
    type: js
  - url: /local/kiosk-config.js
    type: js
  - type: module
    url: >-
      https://cdn.jsdelivr.net/gh/custom-cards/spotify-card@1.6/dist/spotify-card.umd.js
  - url: /local/custom-lovelace/air-purifier/card.js
    type: module
  - url: /local/custom-lovelace/mini-graph-card-bundle.js
    type: module
  - url: /local/vertical-stack-in-card.js?v=0.1.3.1
    type: js


