---
- platform: generic_thermostat
  name: Master Bedroom
  heater: switch.office_heater_tplink
  target_sensor: sensor.master_bedroom_temperature
  target_temp: 18.0

- platform: generic_thermostat
  name: Adas Room
  heater: switch.adas_room_heater
  target_sensor: sensor.adas_room_temperature
  target_temp: 18.0

- platform: generic_thermostat
  name: Lenis Room
  heater: switch.lenis_room_heater
  target_sensor: sensor.lenis_room_temperature
  target_temp: 18.0
