---
- platform: template
  sensors:
    air_purifier_speed:
      value_template: "{{ states.fan.xiaomi_miio_device.attributes.speed }}"
    air_purifier_temperature:
      value_template: "{{ states.fan.xiaomi_miio_device.attributes.temperature }}"
      unit_of_measurement: '°C'
      icon_template: mdi:thermometer
    air_purifier_humidity:
      value_template: "{{ states.fan.xiaomi_miio_device.attributes.humidity }}"
      unit_of_measurement: '%'
      icon_template: mdi:water-percent
    air_purifier_air_quality:
      value_template: "{{ states.fan.xiaomi_miio_device.attributes.aqi }}"
      icon_template: mdi:air-filter
      unit_of_measurement: 'aqi'
