- platform: rest
  name: ferm_fridge_beer_temp
  resource: !secret ferm_fridge_api
  # value_template: '{{ value_json[0].beer_temp }}'
  value_template: '{{ value_json[0].beer_temp | replace("&deg; C", "") }}'

- platform: rest
  name: ferm_fridge_chamber_temp
  resource: !secret ferm_fridge_api
  value_template: '{{ value_json[0].chamber_temp | replace("&deg; C", "") }}'

- platform: rest
  name: ferm_fridge_shed_temp
  resource: !secret ferm_fridge_api
  value_template: '{{ value_json[0].room_temp | replace("&deg; C", "") }}'
