- platform: history_stats
  name: Adas screen time
  entity_id: media_player.living_room_tv
  state: "playing"
  type: time
  start: "{{ now().replace(hour=6, minute=0, second=0) }}"
  end: "{{ now().replace(hour=19, minute=0, second=0) }}"

- platform: history_stats
  name: Dannys Mobile Time
  entity_id: binary_sensor.pixel_3a_interactive
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: Time at home Danny
  entity_id: person.danny
  state: "home"
  type: ratio
  duration:
    days: 14
  end: "{{ now() }}"

- platform: history_stats
  name: Time at home Gemma
  entity_id: person.gemma
  state: "home"
  type: ratio
  duration:
    days: 14
  end: "{{ now() }}"

- platform: template
  sensors:
    hours_outside_per_day_gemma: # XXX: fails when returns "0m"
      friendly_name: Hours out of house Gemma
      value_template: >
        {% set value = state_attr("sensor.time_at_home_gemma", "value") %}
        {% if value != None %}
        {% set d, h, m = value.split() %}
        {% set d, h, m = d[:-1] | int, h[:-1] | int, m[:-1] | int %}
        {% set hours_outside = ((14 - d) * 86400 - h * 3600 - m * 60) / 3600 %}
        {{ (hours_outside / 14) | round(1) }}
        {% endif %}

    hours_outside_per_day_danny: # XXX: fails when returns "0m"
      friendly_name: Hours out of house Danny
      value_template: >
        {% set value = state_attr("sensor.time_at_home_danny", "value") %}
        {% if value != None %}
        {% set d, h, m = value.split() %}
        {% set d, h, m = d[:-1] | int, h[:-1] | int, m[:-1] | int %}
        {% set hours_outside = ((14 - d) * 86400 - h * 3600 - m * 60) / 3600 %}
        {{ (hours_outside / 14) | round(1) }}
        {% endif %}

    no_one_home:
      friendly_name: No one home
      value_template: >
        {{ not is_state("person.danny", "home")
            and not is_state("person.gemma", "home") }}
