---
- platform: min_max
  name: "Home Average Temperature"
  type: mean
  round_digits: 1
  entity_ids:
  - sensor.adas_room_temperature
  - sensor.lenis_room_temperature

- platform: min_max
  name: "Home Average Temperature"
  type: mean
  round_digits: 1
  entity_ids:
  - sensor.adas_room_temperature
  - sensor.lenis_room_temperature
