---
- platform: min_max
  name: "Home Average Temperature"
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.adas_room_sensor_temperature
    - sensor.lenis_room_sensor_temperature
    - sensor.family_room_sensor_temperature

- platform: template
  sensors:
    preferred_temperature:
      friendly_name: "Outside Temperature"
      unit_of_measurement: "째C"
      value_template: >
        {% if states('sensor.deck_temperature') not in ['unknown', 'unavailable'] %}
          {{ states('sensor.deck_temperature') }}
        {% else %}
          {{ states('sensor.melbourne_temperature') }}
        {% endif %}

- platform: template
  sensors:
    preferred_temperature:
      friendly_name: "Inside Temperature"
      unit_of_measurement: "째C"
      value_template: >
        {{ states('sensor.family_room_sensor_temperature') }}

- platform: rest
  name: Beer Temperature
  resource: !secret ferm_fridge_api
  # value_template: '{{ value_json[0].beer_temp }}'
  value_template: '{{ value_json[0].beer_temp | replace("&deg; C", "") }}'
  unit_of_measurement: "째C"
  icon: "mdi:thermometer"

- platform: rest
  name: Deck Temperature
  resource: !secret ferm_fridge_api
  value_template: '{{ value_json[0].room_temp | replace("&deg; C", "") }}'
  unit_of_measurement: "째C"
  icon: "mdi:thermometer"
