- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'
    - 'beat'

- platform: worldclock
  friendly_name: london_time
  time_zone: Europe/London

- platform: worldclock
  friendly_name: nz_time
  time_zone: Pacific/Auckland
