---
- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "time_date"
    - "time_utc"

- platform: worldclock
  time_zone: Europe/London

- platform: worldclock
  time_zone: Pacific/Auckland

- platform: template
  sensors:
    next_sunrise:
      value_template: >
        {{ as_timestamp(state_attr('sun.sun', 'next_rising')) | timestamp_custom('%H:%M', True) }}

    next_sunset:
      value_template: >
        {{ as_timestamp(state_attr('sun.sun', 'next_setting')) | timestamp_custom('%H:%M', True) }}
