- platform: darksky
  api_key: !secret dark_sky_api_key
  forecast:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
  monitored_conditions:
    - icon
    - summary
    - nearest_storm_distance
    - nearest_storm_bearing
    - humidity
    - temperature
    - temperature_high
    - temperature_low
    - apparent_temperature
    - apparent_temperature_high
    - apparent_temperature_low
    - wind_speed
    - wind_bearing
    - precip_type
    - precip_probability
    - precip_accumulation
    - precip_intensity
    - precip_intensity_max
    - uv_index
    - daily_summary
    - pressure
    - visibility

- platform: bom
  monitored_conditions:
    - apparent_t
    - cloud
    - gust_kmh
    - air_temp
    - delta_t
    - rain_trace
    - dewpt
    - rel_hum
    - vis_km
    - weather
    - wind_dir
    - wind_spd_kmh

- platform: bom_forecast
  product_id: IDV10450
  name: Melbourne
  forecast_days: 4
  rest_of_today: True
  friendly: True
  friendly_state_format: '{max}, {summary}'
  monitored_conditions:
    - 'max'
    - 'min'
    - 'chance_of_rain'
    - 'possible_rainfall'
    - 'summary'
    - 'detailed_summary'
