- alias: "Bedtime routine"
  trigger:
    - platform: time
      at: "21:20:00"
  action:
    - condition: state
      entity_id: light.living_room_lamp
      state: "on"
    - service: light.set_brightness
      data:
        entity_id: light.living_room_lamp
        brightness: 0.2
