name: Configuration Check
on: [push, pull_request]
jobs:
  home-assistant:
    name: Home Assistant Core Configuration Check
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@v3
      - name: 🚀 Run Home Assistant Configuration Check
        uses: frenck/action-home-assistant@v1.4
        with:
          path: "."
          secrets: secrets_ci.yaml
          version: stable
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11 #install the python needed
          - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          ref: # branch
            my_other_branch
      - name: execute py script # run file
        run: |
          python scripts/check_secrets.py
